# services:
#   postgres:
#     image: postgres:16
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: ktaxes
#     ports:
#       - '5432:5432'



version: '3'

networks:
  tax-api:
    driver: bridge

services:
    tax-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env
        networks:
            - tax-api
    db:
        image: postgres:16.0
        environment:
            POSTGRES_DB: ktaxes
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"
        networks:
            - tax-api
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]

# volumes:
#     pgdata:
